
import { ShieldAlert } from 'lucide-react';

export default function DisclaimerPage() {
  return (
    <div className="container mx-auto py-8 px-4 md:px-6">
      <header className="text-center mb-12">
        <ShieldAlert className="h-16 w-16 text-primary mx-auto mb-4" />
        <h1 className="text-4xl font-bold tracking-tight sm:text-5xl font-headline text-primary">
          Disclaimer
        </h1>
        <p className="mt-4 text-xl text-foreground/80 max-w-3xl mx-auto text-balance">
          Important information regarding your use of FinanceForward.
        </p>
      </header>

      <div className="max-w-3xl mx-auto space-y-8 bg-card p-6 sm:p-8 rounded-xl shadow-lg text-foreground/80">
        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">1. For Educational & Informational Purposes Only</h2>
          <p className="leading-relaxed text-balance">
            The content provided on FinanceForward, including all calculators, projections, articles, and data, is intended for informational and educational purposes only. It is not, and should not be construed as, financial, investment, legal, tax, or any other form of professional advice.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">2. No Financial Advice</h2>
          <p className="leading-relaxed text-balance">
            FinanceForward is not a financial advisor. The tools and information provided are generic in nature and may not be applicable to your individual financial circumstances. You should not make any financial decisions based solely on the information presented on this website. We strongly recommend that you consult with a qualified and licensed financial professional before making any investment or financial planning decisions.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">3. Accuracy and Completeness of Information</h2>
          <p className="leading-relaxed text-balance">
            While we strive to provide accurate and up-to-date information, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the information, tools, or related graphics contained on the website. Data, especially real-time cryptocurrency prices fetched from third-party APIs like Gemini, is subject to change and may contain inaccuracies or delays. Any reliance you place on such information is therefore strictly at your own risk.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">4. Investment Risks</h2>
          <p className="leading-relaxed text-balance">
            All investments, including cryptocurrencies, carry a risk of loss. The value of investments can go down as well as up, and you may not get back the amount you originally invested. Past performance is not an indicator of future results. The speculative future value projections generated by our Cryptocurrency Investment Calculator are based on a simplified model and assumptions; they are not guarantees of future performance and should be treated as illustrative examples only.
          </p>
        </section>
        
        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">5. Limitation of Liability</h2>
          <p className="leading-relaxed text-balance">
            In no event will FinanceForward or its creators be liable for any loss or damage, including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this website.
          </p>
        </section>

        <p className="text-center font-semibold text-foreground/90 pt-4">
          By using this application, you acknowledge that you have read, understood, and agree to this disclaimer.
        </p>
      </div>
    </div>
  );
}
